// constants
const API = "/api/"
const VERSION = "v1/"
const USER = "user/"
const PROJECT = "project/"
const ARTICLE = "article/"
const FILE = "file/"
const EMAIL = "email/"
const VERIFY = "verify/"
const CONTACTUS = "contactus"
const BRIEF = "brief/"
const SUBSCRIBER = "subscriber"
const SUBSCRIBERS = "subscribers"
const CHECKOUT = "checkout/"
const SESSION = "session"
const ACCOUNT = "account/"
const RESET = "reset"
const TOKEN = "token"
const PASSWORD = "password"
const AUTHENTICATE = "authenticate/"
const COUPON = "coupon"
const TICKET = "ticket"
const TICKETS = "tickets"
const COMMENT = "comment"
const ADMIN = "admin/"
const USERS = "users"
const BACKEND_SERVER_HOST = process.env.VUE_APP_EMAIL_ACTION_BACKEND_SERVICE_ENDPOINT
const BACKEND_SERVER_PORT = process.env.VUE_APP_EMAIL_ACTION_BACKEND_PORT

// api endpoints
const API_ENDPOINTS = {
    AUTHENTICATE: BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + AUTHENTICATE,
    RESET_PASSWORD: BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + AUTHENTICATE + RESET,
    IS_TOKEN_VALID: BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + AUTHENTICATE + TOKEN,
    UPDATE_PASSWORD: BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + AUTHENTICATE + PASSWORD,
    SIGN_UP: BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + "register/",
    READ_USER: function(email){return BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + USER + email},
    CHANGE_PASSWORD: BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + USER + "change_password",
    UPDATE_USER_INFO: function(email){return BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + USER + email},
    READ_PROJECTS: BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + "projects",
    UPDATE_PROJECT: BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + PROJECT,
    CREATE_PROJECT: BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + PROJECT,
    DELETE_PROJECT: function(email, projectId){return BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + PROJECT + email + "/" + projectId},
    READ_PROJECT: function(email, projectId) {return BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + PROJECT + email + "/" + projectId},
    READ_ARTICLES: BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + "articles",
    CREATE_ARTICLE: BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + ARTICLE,
    UPDATE_ARTICLE: BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + ARTICLE,
    DELETE_ARTICLE: function(email, projectId, articleId){return BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + ARTICLE + email + "/" + projectId + "/" + articleId},
    UPLOAD_FILE: BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + "file",
    LIST_FILES: function(email) {return BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + FILE + email},
    DELETE_FILE: function(email, fileName) {return BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + FILE + email + "/" + fileName},
    IS_EMAIL_VERIFIED: function(email) {return BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + EMAIL + VERIFY + email},
    SEND_VERIFICATION_EMAIL: function(email) {return BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + EMAIL + VERIFY + email},
    SEND_EMAIL: BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + EMAIL + "send",
    CONTACT_US: BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + EMAIL + CONTACTUS,
    READ_PROJECT_BRIEF: function(projectId) {return BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + BRIEF + projectId},
    CREATE_SUBSCRIBER: BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + SUBSCRIBER,
    UPDATE_SUBSCRIBER: BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + SUBSCRIBER,
    DELETE_SUBSCRIBER: function(projectId, email){return BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + SUBSCRIBER +"/" + projectId + "/" + email},
    READ_SUBSCRIBERS: BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + SUBSCRIBERS,
    SEARCH_SUBSCRIBERS: BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + SUBSCRIBERS,
    CHECKOUT_CREATE_SESSION: BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + CHECKOUT + SESSION,
    CANCEL_SUBSCRIPTION: function(email, subscriptionId) {return BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + CHECKOUT + email + "/" + subscriptionId},
    UPDATE_SUBSCRIPTION: function(email, subscriptionId) {return BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + CHECKOUT + email + "/" + subscriptionId},
    READ_ACCOUNT_INFO: function(email) {return BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + ACCOUNT + email},
    READ_COUPON: function(coupon) {return BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + CHECKOUT + COUPON + "?couponId=" + coupon},
    READ_TICKETS: BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + TICKETS,
    CREATE_TICKET: BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + TICKET,
    UPDATE_TICKET: function(ticketId) {return BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + TICKET + "/" + ticketId},
    DELETE_TICKET: function(email, ticketId) {return BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + TICKET + "/" + email + "/" + ticketId},
    CREATE_COMMENT: BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + COMMENT,
    ADMIN_READ_USERS: BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + ADMIN + USERS,
    ADMIN_SEARCH_USERS: BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + ADMIN + USERS,
    ADMIN_READ_TICKETS: BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + ADMIN + TICKETS,
    ADMIN_SEARCH_TICKETS: BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + ADMIN + TICKETS,
    ADMIN_UPDATE_USER: BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + ADMIN + USER,
    ADMIN_READ_SUBSCRIBERS: BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + ADMIN + SUBSCRIBERS,
    ADMIN_SEARCH_SUBSCRIBERS: BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + ADMIN + SUBSCRIBERS,
    ADMIN_UPDATE_SUBSCRIBER: BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + ADMIN + SUBSCRIBER,
    ADMIN_DELETE_SUBSCRIBER: BACKEND_SERVER_HOST + BACKEND_SERVER_PORT + API + VERSION + ADMIN + SUBSCRIBER,
}

export default API_ENDPOINTS